url: https://aptanadev.github.io
baseurl: /topengtheevent/

# Site settings
title: Topeng the Event
email: topeng_eo@topengeo.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
social:
  - title: facebook
    url: https://www.facebook.com/share/1EqDMc3jQZ/
  - title: instagram
    url: https://www.instagram.com/topeng_eo?igsh=eHFieXgydm5vZmU0
  - title: youtube
    url: https://youtube.com/@topengeo9481?si=mP5kxs1E9z6H_4bw

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
